codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 90%  # Min coverage
    patch:
      default:
        target: 90%  # Min coverage per PR

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true
